### ISSUE TITLE
Summer 2024: Tasks

### ISSUE THREAD

**Issue by Thompson632** [What-Should-I-Eat/WSIE#165]
# 2024 Summer Tasks

## General
- [ ] Fix eye icon - bug with bootstrap/jquery version
- [ ] After verification successful, allow auto login (requires server changes because of the cookies)
- [ ] If user tries to access different webpage, redirect back to home and show an alert saying to login
- [ ] Fix/rework web scraping for preparation steps
- [ ] Decompose endpoints.js into individual routes based on the functionality
- [ ] Refactor legacy tests for new client. When complete, remove all legacy source 
- [ ] Update client/server so you can run standalone from docker

## New Features
- [ ] Add filter button on recipe search page. Thinking that we have the filter include all available fields for edamam api
- [ ] Paginate through more results
- [ ] Add some indicator to a recipe in the my recipes page if a user created
- [ ] Add ability to update/edit a recipe
- [ ] Add feature to export recipes in PDF. This would require sizable amount of work because of the current way data is stored
- [ ] Show user created recipes with edamam search results
- [ ] Add feature if user selects a user created recipe... if they own the recipe, they can delete it. If they don't they can favorite/unfavorite. If the owner deletes, we need to clear the recipe from all other users who favorite it

## Mobile App
- [ ] Add UI/UX to mobile app
- [ ] Refactor mobile app to align with new client features and functionality (look and feel, alerts, directory structure, common code sharing)

## CI/CD
- [ ] Kubernetes deployment to cloud (stretch(
- [ ] Auto deployment from repository merge to main

**Comment by nicksonsini97** [comment]
Totally up to you if you want to view it on a real Expo app on your phone or not, but if so the Expo app functionality would require the following tasks:
- updating all localhost calls to be local IP network instead
- incorporating [<keyboardavoidingview>](https://reactnative.dev/docs/keyboardavoidingview) if applicable (essentially for inputs lower on the screen, it makes it so when a real iPhone clicks in the box, the context shifts up so that the keyboard doesn't block the text box input)
- in addition to UI/UX styling, probably makes sense to make certain sizing things relative as I had only been doing absolute size (based on an iPhone 14 Pro Max, which probably is on the bigger size for mobile devices)

**Comment by Thompson632** [comment]
Decomposed this issue into multiple
